### ISSUE TITLE
RefreshボタンでAlertを出して欲しい

### ISSUE THREAD

**Issue by abekdwight** [MingSiro71/homework_viewer#1]
お疲れ様です。チュータの阿部です。

使いやすいフィードバックエディタを作成していただき有難うございます。

使用しているときに誤ってRefreshボタンを押してしまい変更を全て消してしまいました。
Refreshボタンを押した際にAlert等でダイアログボックスが出るとありがたいです。。。
ちなみにこのプロジェクトのソースコードはあるでしょうか？
よろしくお願いします。

**Comment by MingSiro71** [comment]
早速のフィードバックありがとうございます。

そうですね、確かにうっかり消してしまいそうです。
Refreshを使うと想定される状況ではfeedbackが空になっているはずなので、
feedbackが空でないときにAlertを出すよう変更を予定しておきます。

ソースコードはこのリポジトリに上がっているものが全てです。
あとは呼び出しているAPIの仕様通りに動かしています。

**Comment by abekdwight** [comment]
ありがとうございます！！

> ソースコードはこのリポジトリに上がっているものが全てです。

そうだったのですか。トランスパイルされたものかと勘違いしていました。
Markdownなどにも対応できると嬉しいのでPRを送れるように自分なりに書いて見たいと思います！！

**Comment by MingSiro71** [comment]
ひとまず、確認アラートを実装しました。
node.jsのフロント開発環境はよくわからないのでぜひイマドキなコードにおねがいします！
